### PR TITLE
Feat/dockerization

### PR DESCRIPTION
**Pull request by Lirt**
This merge request add possibilty to use postfwd in Docker container.

Postfwd Docker container runs with default arguments, which can be overriden as usually in docker command `docker run`. Nice thing about having postfwd in Docker container is that you are keeping your system packages clean. This also makes installation very simple on OSs where postfwd must be installed manually (RH based or other). 

Postfwd cannot be run straightforward as CMD/ENTRYPOINT, because it creates master process which spawns childs and then exits which causes whole container to exit with it. If Postfwd had option to keep master process in foreground, then script `docker-entrypoint.sh` would not be necessary.

Because of this, I used `sleep infinity` the end of script `docker-entrypoint.sh` to keep process alive.

> Ugliest thing about this is that I needed to use some placeholder command to keep entrypoint script alive and that command is `tail -f -n0 -q /dev/null`. 
> 
> Discussion about this issue: https://stackoverflow.com/questions/25775266/how-to-keep-docker-container-running-after-starting-services/30632659#30632659

I would like to ask you to create DockerHub repository to make webhook for GitHub. This will cause DockerHub to recreate container on commits into selected branch. Path must be updated to /docker.

As second thing it will allow to download postfwd straight from DockerHub without building. This is very nice because I can inherit this container in my postfwd plugin repository, where I will take it as base image and install all dependencies very easily, which will in the end simplify usage of that plugin.

This can be done for other purposes of course.

### CODE REVIEW

**Comment by Lirt** [comment]
Please, first look at https://github.com/postfwd/postfwd/pull/1. I need README merged in order to update documentation about usage of Docker before merging this.

**Comment by Lirt** [comment]
Hello Jan,

I rebased the commit and updated also `README.md` with instructions on how to pull, build and use Docker container. 

If the URI to docker will be different (I defined it as `postfwd/postfwd`), I will amend my commit with correct URI.

I defined your email in maintainer section, if you would like to use different, please update it or let me know and I will change it. 

I still didn't test this properly. Could postfwd be tested using client you made in `tools/postfwd-client.pl`? I found it recently, but never tried it. I will try to look into it, but if you have some quick notes on usage, point me in right way please :-). Could it be theoretically also used to create simple automated tests to my anti-spam plugin?

Downsides:
* We should install postfwd directly from this repository, not from debian packages. This way we can use different base images and create multiple tags for specific versions, if you needed. I think this can be easily changed in future if there was need.

**Comment by jpkessler** [comment]
Hi Ondrej,

simple functional tests are quiet easy. Please take a look at [http://postfwd.org/doc.html#testing](http://postfwd.org/doc.html#testing).

Of course you can use postfwd-client.pl for that, too. But it's main purpose was performance testing. Syntax (copied from code):

```
my $syntax = "USAGE: client.pl [ OPTIONS ] <addr>:<port>";
GetOptions( \%options,
  'verbose|v+',
  'quiet|q+',
  'process|p=i',
  'count|c=i',
  'timeout|t=i',
  'file|f=s',
) or die "$syntax\n";
```

Means that:

`postfwd-client.pl -c100 -p10 127.0.0.1:10040`

will create 10 processes, each sending 100 requests to localhost on port 10040.

And just to sharpen my understanding: Am I right that postfwd1 should have anything to run in a docker without "wrapper-script"?

```
postfwd -h
            ...
            -d, --daemon        run postfwd as daemon (must be skipped for docker!)
            -L, --stdout        redirect syslog messages to stdout
            ...

```

**Comment by jpkessler** [comment]
_whoops, sent unfinished.._

I'm thinking about introducing a --docker option so that the "wrapper" won't be needed anymore.

The docker URI `postfwd/postfwd` fits for me. Thank you for the updated `README.md`.

Would you be interested to be listed as postfwd docker maintainer?

**Comment by Lirt** [comment]
I think that when you run postfwd, it must stay in foreground, so maybe option for staying in foreground. 

For example, when I run postfwd with `--daemon` or without `--daemon` option, it doesn't stay in foreground. That is the reason why Docker container exits. I don't understand what is daemon option for then.

```bash
/usr/sbin/postfwd2 \
    --file /etc/postfwd/postfwd.cf \
    --user postfw \
    --group postfw \
    --stdout
```

Changing daemon option, wouldn't be backwards compatible, so I guess foreground option seems better.

But actually I found mention about `--nodaemon` option, which keeps postfwd in foreground. I don't know what else this option changes, but it looks like the way. 

Maybe running without `--daemon` doesn't work as intended and keeps --daemon as default?

**Comment by jpkessler** [comment]
Merry Christmas, something got done :)

There were some code changes required to get the logs to stdout and to allow `postfwd2` to say in foreground. Please check out the new `1.36-devel`1 versions. You can find them at

     [http://postfwd.org/DEVEL/postfwd1-1.36-devel1](http://postfwd.org/DEVEL/postfwd1-1.36-devel1)
          and
     [http://postfwd.org/DEVEL/postfwd2-1.36-devel1](http://postfwd.org/DEVEL/postfwd2-1.36-devel1)

or the new `testing`-branch here on github. I've also included a `docker`-directory with an example `Dockerfile` and `docker-compose.yml`. These are just for testing. If you can confirm, that it works as expected, I could integrate your readme, changes and update docs and master-branch.

**Comment by jpkessler** [comment]
Set up a 1st one-pager at [http://postfwd.org/docker/](http://postfwd.org/docker/). Cheers!

**Comment by Lirt** [comment]
Merry Christmas Jan,

I will look into it, and test it in the following days :-).

**Comment by Lirt** [comment]
Also when I run `postfwd2` with command below, I can not interrupt it with `Ctrl+C`. This works fine when I use `postfwd1`.

```bash
docker run -it postfwd-testing:latest /opt/postfwd/sbin/postfwd2 --file /etc/postfwd/postfwd.cf \
        --user postfw \
        --group postfw \
        --server_socket tcp:0.0.0.0:10040 --cache_socket=unix::/var/lib/postfwd.cache \
        --pidfile=/var/lib/postfwd/postfwd.pid --save_rates=/var/lib/postfwd/postfwd.rates \
        --cache=0 --no_parent_dns_cache --noidlestats \
        --stdout --nodaemon

[postfwd2][1][LOG info]: postfwd2 1.36-devel1 starting
[postfwd2][1][LOG info]: Started cache at pid 9
2018/12/26-13:58:38 postfwd2::cache (type Net::Server::Multiplex) starting! pid(9)
[postfwd2][1][LOG info]: Started server at pid 10
2018/12/26-13:58:38 postfwd2::server (type Net::Server::PreFork) starting! pid(10)
Binding to UNIX socket file "/var/lib/postfwd.cache"
Binding to TCP port 10040 on host 0.0.0.0 with IPv4
Setting gid to "101 101"
Setting gid to "101 101"
Setting uid to "101"
Setting uid to "101"
[postfwd2/cache][9][LOG info]: ready for input
[postfwd2/policy][10][LOG info]: ready for input


^C2018/12/26-13:58:40 Server closing!
2018/12/26-13:58:40 Server closing!

[postfwd2/master][1][LOG warning]: warning: can not open socket to :/var/lib/postfwd.cache: 'Connection refused' 'connect: Connection refused'?
[postfwd2/master][1][LOG crit]: cache-daemon check failed 1 times - respawning in 4 seconds
[postfwd2/master][1][LOG info]: Started cache at pid 21
2018/12/26-13:59:42 postfwd2::cache (type Net::Server::Multiplex) starting! pid(21)
[postfwd2/master][1][LOG warning]: warning: can not open socket to 0.0.0.0:10040: 'Connection refused' 'IO::Socket::INET: connect: Connection refused'?
[postfwd2/master][1][LOG crit]: server-daemon check failed 1 times - respawning in 4 seconds
Binding to UNIX socket file "/var/lib/postfwd.cache"
Setting gid to "101 101"
Setting uid to "101"
[postfwd2/master/cache][21][LOG info]: ready for input
[postfwd2/master][1][LOG info]: Started server at pid 22
2018/12/26-13:59:47 postfwd2::server (type Net::Server::PreFork) starting! pid(22)
Binding to TCP port 10040 on host 0.0.0.0 with IPv4
Setting gid to "101 101"
Setting uid to "101"
[postfwd2/master/policy][22][LOG info]: ready for input
```

**Comment by jpkessler** [comment]
Hi Ondrej,

I was blind: There's a typo in the Dockerfile:

`--cache_socket=unix::/var/lib/postfwd.cache`

must be

`--cache_socket=unix::/var/lib/**postfwd/**postfwd.cache`

More after work.

Thanks for your time and suggestions!

**Comment by jpkessler** [comment]
Thanks, I agree that we should drop `"apt-get install postfwd"`. I'm currently at 35C3 (Chaos Communication Congress) and will update the Repo as soon as I'm back.

**Comment by jpkessler** [comment]
Hi, today I released the new version 1.36 of postfwd containing official docker support. I also created a postfwd organisation and repo @Dockerhub. So this pull request will be closed. More infos at postfwd.org and postfwd.org/docker. The final change for docker integration was postfwd2 catching SIGINT (to be stopped when pressing CTRL+C in "-it" mode. Thank you very much for your work and suggestions. Kind regards, Jan

**Pull request closed without merging**
